version: '3.8'

services:
  product_db:
    image: postgres:15-alpine
    container_name: product_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    networks:
      - oms-network

  inventory_db:
    image: postgres:15-alpine
    container_name: inventory_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data
    networks:
      - oms-network

  order_db:
    image: postgres:15-alpine
    container_name: order_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5434:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - oms-network

  user_db:
    image: postgres:15-alpine
    container_name: user_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5435:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - oms-network

networks:
  oms-network:
    driver: bridge

volumes:
  product_db_data:
  inventory_db_data:
  order_db_data:
  user_db_data:
