apiVersion: v1
kind: Namespace
metadata:
  name: cosmos-ecommerce
---
apiVersion: v1
kind: Service
metadata:
  name: product-db
  namespace: cosmos-ecommerce
spec:
  ports:
    - port: 5432
  selector:
    app: product-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-db
  namespace: cosmos-ecommerce
spec:
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: product_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  namespace: cosmos-ecommerce
spec:
  ports:
    - port: 5432
  selector:
    app: inventory-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db
  namespace: cosmos-ecommerce
spec:
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: inventory_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: cosmos-ecommerce
spec:
  ports:
    - port: 5432
  selector:
    app: order-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: cosmos-ecommerce
spec:
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: order_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: cosmos-ecommerce
spec:
  ports:
    - port: 5432
  selector:
    app: user-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: cosmos-ecommerce
spec:
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: user_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
